import Head from "next/head";
import Link from "next/link";
import { Rubik } from "next/font/google";
import clsx from "clsx";
import { useEffect, useState } from "react";

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Home() {
  const [showIframe, setShowIframe] = useState(false);
  const [samlTokenStatus, setSamlTokenStatus] = useState("");
  const fetchSamlToken = async () => {
    setSamlTokenStatus("Fetching SAML token...");
    const resp = await fetch("https://child-pardomain.vercel.app/api/saml", {
      method: "POST",
      credentials: "include",
    });
    const respJson = (await resp.json()) as {
      message?: string;
      samlToken?: string;
    };
    setSamlTokenStatus("SAML token fetched!");
    return respJson;
  };
  useEffect(() => {
    fetchSamlToken()
      .then((resp) => {
        if (resp.samlToken) {
          setShowIframe(true);
        }
      })
      .catch((err) => console.error(err));
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx("flex min-h-screen flex-col", font.className)}>
        <nav className="bg-green-50 px-20 py-4">
          <div className="text-xl font-semibold text-gray-700">
            Parent App -{" "}
            <span className="inline-block rounded bg-gray-500 px-2 py-0.5 font-mono text-white">
              Cookie on .vercel.app
            </span>
          </div>
        </nav>
        <div className="my-4">{samlTokenStatus}</div>
        {showIframe && (
          <div className="overflow-hidden px-20 py-4">
            <iframe
              src="https://child-pardomain.vercel.app/banking"
              className="h-[50dvh] w-full rounded shadow"
            />
          </div>
        )}
      </main>
    </>
  );
}
